[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip STM32F072CBTx"
linker = "flip-link"

[target.thumbv7em-none-eabihf]
runner = "probe-rs run --chip STM32F405RGTx"
linker = "flip-link"

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG="debug"
