[package]
authors = ["Cullen Jennings <fluffy@iii.ca>"]
edition = "2021"
readme = "README.md"
name = "app"
version = "0.1.1"
repository = "git@github.com:fluffy/bare-rust.git"
license = "BSD-2-Clause"

[dependencies]

[lib]
name = "hal"
path = "src/hal.rs"
bench = false
test = false

[[bin]]
name = "app"
test = false
bench = false

[profile.release]
debug = "limited"
opt-level = "s"
lto = "fat"
panic = "abort"

[profile.dev]
opt-level = 3
debug = true
strip = "none"

[features]
default = [ "brd-blink-clk-a" ]
#default = [ "brd-hactar-10" ]
brd-hactar-10 = []
brd-blink-clk-a = []


