[package]
authors = ["Cullen Jennings <fluffy@iii.ca>"]
edition = "2021"
readme = "README.md"
name = "app"
version = "0.1.0"
repository = "git@github.com:fluffy/bare-rust.git"
license = "BSD-2-Clause"

[dependencies]

[lib]
name = "hal"
path = "src/lib/hal/hal.rs"
bench = false
test = false


[[bin]]
name = "app"
test = false
bench = false

[profile.release]
debug = true