[package]
authors = ["Cullen Jennings <fluffy@iii.ca>"]
edition = "2024"
readme = "README.md"
name = "app"
version = "0.1.0"
repository = "git@github.com:fluffy/bare-rust.git"
license = "BSD-2-Clause"

[dependencies]

# this lets you use `cargo fix`!
[[bin]]
name = "app"
test = false
bench = false

[profile.release]
debug = true