[package]
name = "ui-cots"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ui-cots"
test = false
bench = false

[dependencies]
ui-app = { path = "../ui-app" }
cortex-m = "0.7"
cortex-m-rt = "0.7"
panic-halt = "0.2"
stm32f4xx-hal = { version = "0.21", features = ["stm32f405"] }
heapless = "0.8"

[build-dependencies]
