[package]
name = "ui-app"
version = "0.1.0"
edition = "2024"

[dependencies]
bitmap-font = "0.3.0"
defmt = { version = "1.0.1", default-features = false }
embedded-graphics = "0.8.1"
embedded-graphics-core = { version = "0.4.0", default-features = false }
heapless = "0.9.1"
hex = { version = "0.4.3", default-features = false }

[dev-dependencies]
tokio = { version = "1.47.1", features = ["rt", "macros"] }
