
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "arm-none-eabi-gdb -q -x openocd.gdb"
rustflags = [
    #    "-Zemit-stack-sizes",
    "-Clinker-plugin-lto",
    "-Clink-arg=-mllvm=-lto-embed-bitcode=optimized",
    "-Clink-arg=-mllvm=-stack-size-section",
    "-Clink-arg=-Tlinker.ld",
]

[build]
#target = "thumbv7em-none-eabihf" # Cortex-M4F

[test]

[unstable]
build-std = ["compiler_builtins", "core"]


