[target.thumbv7em-none-eabihf]
#runner = "qemu-system-arm -cpu cortex-m4 -machine netduinoplus2 -nographic -semihosting-config enable=on,target=native -kernel"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "arm-none-eabi-gdb -q -x openocd.gdb"

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F
rustflags = ["-C", "link-arg=-Tlinker.ld"]
