[target.thumbv7em-none-eabihf]
#runner = "qemu-system-arm -cpu cortex-m4 -machine netduinoplus2 -nographic -semihosting-config enable=on,target=native -kernel"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "arm-none-eabi-gdb -q -x openocd.gdb"
rustflags = [
    #    "-Zemit-stack-sizes",
    "-Clinker-plugin-lto",
    "-Clink-arg=-mllvm=-lto-embed-bitcode=optimized",
    "-Clink-arg=-mllvm=-stack-size-section",
    "-Clink-arg=-Tlinker.ld",
]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F

[test]
target = "aarch64-apple-darwin"
rustflags = [
    "-Clink-arg=-mllvm=-lto-embed-bitcode=optimized",
]

[unstable]
build-std = ["compiler_builtins", "core"]


