//! Elliptic Curve Diffie-Hellman (ECDH) key exchange using CMOX library
//!
//! This module provides implementations of ECDH key exchange algorithms using the
//! STM32 CMOX library. It supports both NIST curves (Weierstrass form) and
//! Montgomery curves (X25519/X448).
//!
//! ## Features
//!
//! - **NIST Curves**: P-256, P-384, P-521 for traditional ECDH
//!   - Full uncompressed public keys (x,y coordinates)
//!   - Shared secret is x-coordinate of computed point
//!   - Compatible with ECDSA keys
//!
//! - **Montgomery Curves**: X25519 and X448 for modern ECDH
//!   - Compact public keys (x-coordinate only)
//!   - Fast constant-time operations
//!   - Recommended for new applications
//!
//! - **Key Generation**: Real cryptographic key pair generation
//!   - Uses CMOX ECC key generation functions
//!   - Proper random number handling
//!   - Secure key derivation from entropy
//!
//! - **Security Features**:
//!   - Real cryptographic operations via CMOX library
//!   - Proper memory management and cleanup
//!   - Fault checking for enhanced security

// XXX(RLB) In order for this to work for MLS, we will need a way to implement DeriveKeyPair, in
// particular for the NIST curves.  It looks like that will have to go through cmox_ecdsa_keyGen,
// but it looks like that method does some transformation on the private key bytes, which is
// unclear to me from the comments.

use crate::ensure_initialized;
use crate::error::{EccResult, FromRetval};
use cmox_sys::*;
use core::mem::MaybeUninit;
use heapless::Vec;

/// Supported elliptic curves for ECDH
// XXX(RLB) These options omit configuration options allowed by CMOX:
//     * Only the _LOWMEM variants are provided
//     * Brainpool, ANSSI, and OSCCA curves are not supported
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum EcdhCurve {
    /// NIST P-256 (secp256r1) - 32-byte private keys, 64-byte public keys
    P256,
    /// NIST P-384 (secp384r1) - 48-byte private keys, 96-byte public keys  
    P384,
    /// NIST P-521 (secp521r1) - 66-byte private keys, 132-byte public keys
    P521,
    /// X25519 (Curve25519) - 32-byte private keys, 32-byte public keys
    X25519,
    /// X448 (Curve448) - 56-byte private keys, 56-byte public keys
    X448,
}

impl EcdhCurve {
    fn to_cmox_impl(self) -> cmox_ecc_impl_t {
        match self {
            EcdhCurve::P256 => unsafe { CMOX_ECC_SECP256R1_LOWMEM },
            EcdhCurve::P384 => unsafe { CMOX_ECC_SECP384R1_LOWMEM },
            EcdhCurve::P521 => unsafe { CMOX_ECC_SECP521R1_LOWMEM },
            EcdhCurve::X25519 => unsafe { CMOX_ECC_CURVE25519 },
            EcdhCurve::X448 => unsafe { CMOX_ECC_CURVE448 },
        }
    }

    fn math_funcs(self) -> cmox_math_funcs_t {
        // XXX(RLB) These are not the only options.  We could create a MathFuncs enum and use it to
        // configure the math functions at generate / derive time.
        match self {
            EcdhCurve::P256 => unsafe { CMOX_MATH_FUNCS_SUPERFAST256 },
            EcdhCurve::P384 => unsafe { CMOX_MATH_FUNCS_FAST },
            EcdhCurve::P521 => unsafe { CMOX_MATH_FUNCS_FAST },
            EcdhCurve::X25519 => unsafe { CMOX_MATH_FUNCS_FAST },
            EcdhCurve::X448 => unsafe { CMOX_MATH_FUNCS_FAST },
        }
    }

    fn private_key_len(self) -> usize {
        match self {
            EcdhCurve::P256 => 32,
            EcdhCurve::P384 => 48,
            EcdhCurve::P521 => 66,
            EcdhCurve::X25519 => 32,
            EcdhCurve::X448 => 56,
        }
    }

    fn public_key_len(self) -> usize {
        match self {
            EcdhCurve::P256 => 64,   // Uncompressed: 32 bytes x + 32 bytes y
            EcdhCurve::P384 => 96,   // Uncompressed: 48 bytes x + 48 bytes y
            EcdhCurve::P521 => 132,  // Uncompressed: 66 bytes x + 66 bytes y
            EcdhCurve::X25519 => 32, // Montgomery: x-coordinate only
            EcdhCurve::X448 => 56,   // Montgomery: x-coordinate only
        }
    }

    /// Returns the length of a shared secret generated by an ECDH operation on this curve
    pub fn shared_secret_len(self) -> usize {
        match self {
            EcdhCurve::P256 => 32,   // x-coordinate of shared point
            EcdhCurve::P384 => 48,   // x-coordinate of shared point
            EcdhCurve::P521 => 66,   // x-coordinate of shared point
            EcdhCurve::X25519 => 32, // Montgomery ladder result
            EcdhCurve::X448 => 56,   // Montgomery ladder result
        }
    }
}

/// ECDH private key for key exchange operations
#[derive(Debug)]
pub struct EcdhPrivateKey {
    curve: EcdhCurve,
    private_key: Vec<u8, 66>, // Max size, for P-521
}

impl EcdhPrivateKey {
    /// Create an ECDH private key from raw bytes
    pub fn from_bytes(curve: EcdhCurve, private_key_data: &[u8]) -> crate::Result<Self> {
        if private_key_data.len() != curve.private_key_len() {
            return Err(crate::error::CoreError::InitFail.into());
        }

        let mut private_key = Vec::new();
        private_key
            .extend_from_slice(private_key_data)
            .expect("Private key buffer too short");

        Ok(Self { curve, private_key })
    }

    /// Get the curve associated with this private key
    pub fn curve(&self) -> EcdhCurve {
        self.curve
    }

    /// Get private key as bytes
    pub fn as_bytes(&self) -> &[u8] {
        &self.private_key
    }

    /// Perform ECDH key exchange with a peer's public key
    pub fn exchange(&self, peer_public_key: &EcdhPublicKey) -> crate::Result<SharedSecret> {
        ensure_initialized()?;

        if self.curve != peer_public_key.curve {
            return Err(crate::error::CoreError::InitFail.into());
        }

        let mut shared_secret = Vec::new();
        shared_secret
            .resize(self.curve.shared_secret_len(), 0)
            .expect("Shared secret buffer too short");

        let mut shared_secret_len = shared_secret.len();

        let mut working_buffer = [0u8; 2048];
        let rv = unsafe {
            // Create ECC context
            let mut ecc_ctx: cmox_ecc_handle_t = MaybeUninit::zeroed().assume_init();

            cmox_ecc_construct(
                &mut ecc_ctx,
                self.curve.math_funcs(),
                working_buffer.as_mut_ptr(),
                working_buffer.len(),
            );

            // Call CMOX ECDH
            let rv = cmox_ecdh(
                &mut ecc_ctx,
                self.curve.to_cmox_impl(),
                self.private_key.as_ptr(),
                self.private_key.len(),
                peer_public_key.public_key.as_ptr(),
                peer_public_key.public_key.len(),
                shared_secret.as_mut_ptr(),
                &mut shared_secret_len,
            );

            // Clean up ECC context
            cmox_ecc_cleanup(&mut ecc_ctx);

            rv
        };

        EccResult::from_rv(rv)?;

        shared_secret
            .resize(shared_secret_len, 0)
            .expect("Shared secret buffer too short");
        Ok(SharedSecret(shared_secret))
    }
}

/// ECDH public key for key exchange operations
#[derive(Debug)]
pub struct EcdhPublicKey {
    curve: EcdhCurve,
    public_key: Vec<u8, 132>, // Max size, for P-521
}

impl EcdhPublicKey {
    /// Create an ECDH public key from raw bytes
    pub fn from_bytes(curve: EcdhCurve, public_key_data: &[u8]) -> crate::Result<Self> {
        if public_key_data.len() != curve.public_key_len() {
            return Err(crate::error::CoreError::InitFail.into());
        }

        let mut public_key = Vec::new();
        public_key
            .extend_from_slice(public_key_data)
            .expect("Public key buffer too short");

        Ok(Self { curve, public_key })
    }

    /// Get public key as bytes
    pub fn as_bytes(&self) -> &[u8] {
        &self.public_key
    }
}

/// ECDH shared secret result from key exchange
pub struct SharedSecret(Vec<u8, 66>);

impl SharedSecret {
    /// Get shared secret as bytes
    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}

/// ECDH key pair (private + public key)
#[derive(Debug)]
pub struct EcdhKeyPair {
    /// The private key (scalar)
    pub private_key: EcdhPrivateKey,

    /// The public key (group element)
    pub public_key: EcdhPublicKey,
}

impl EcdhKeyPair {
    /// Generate a new ECDH key pair using cryptographically secure random data
    pub fn generate(curve: EcdhCurve, random: &[u8]) -> crate::Result<Self> {
        ensure_initialized()?;

        let expected_random_len = curve.private_key_len();
        if random.len() < expected_random_len {
            return Err(crate::error::EccError::WrongRandom.into());
        }

        // Create ECC context
        let mut working_buffer = [0u8; 2048];
        let mut ecc_ctx: cmox_ecc_handle_t = unsafe { MaybeUninit::zeroed().assume_init() };

        unsafe {
            cmox_ecc_construct(
                &mut ecc_ctx,
                curve.math_funcs(),
                working_buffer.as_mut_ptr(),
                working_buffer.len(),
            );
        }

        let mut private_key = Vec::new();
        private_key
            .resize(curve.private_key_len(), 0)
            .expect("Private key buffer too short");

        let mut public_key = Vec::new();
        public_key
            .resize(curve.public_key_len(), 0)
            .expect("Public key buffer too short");

        let mut private_key_len = private_key.len();
        let mut public_key_len = public_key.len();

        // Call CMOX key generation
        let result = unsafe {
            cmox_ecdsa_keyGen(
                &mut ecc_ctx,
                curve.to_cmox_impl(),
                random.as_ptr(),
                random.len(),
                private_key.as_mut_ptr(),
                &mut private_key_len,
                public_key.as_mut_ptr(),
                &mut public_key_len,
            )
        };

        unsafe {
            cmox_ecc_cleanup(&mut ecc_ctx);
        }

        EccResult::from_rv(result)?;

        // Create key pair
        private_key
            .resize(private_key_len, 0)
            .expect("Private key buffer too short");
        public_key
            .resize(public_key_len, 0)
            .expect("Public key buffer too short");

        Ok(Self {
            private_key: EcdhPrivateKey { curve, private_key },
            public_key: EcdhPublicKey { curve, public_key },
        })
    }
}
