name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
        target: thumbv7em-none-eabi

    - name: Verify the ui-app crate
      uses: ./.github/actions/check-crate
      with:
        path: ./ui-app

    - name: Verify the ui-stm32 crate (ev12)
      uses: ./.github/actions/check-crate
      with:
        path: ./ui-stm32
        run-tests: false
        args: --no-default-features -F ev12

    - name: Verify the ui-stm32 crate (ev13)
      uses: ./.github/actions/check-crate
      with:
        path: ./ui-stm32
        run-tests: false
        args: --no-default-features -F ev12

    - name: Verify the ui-tauri crate
      uses: ./.github/actions/check-crate
      with:
        path: ./ui-tauri/src-tauri
        run-tests: false

