name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build x86
        run: cargo build --verbose --no-default-features  --features board-sim
      - name: Build arm hactar12
        run: cargo build --verbose --no-default-features  --features board-hactar12 --target=thumbv7em-none-eabihf --release
      - name: Build arm blinkA
        run: cargo build --verbose --no-default-features  --features board-blinkA --target=thumbv7em-none-eabihf --release
      - name: Run tests
        run: cargo test --verbose --no-default-features  --features board-sim
      - name: Run emulator test
        run: cargo build --no-default-features  --features board-qemu,exit --target=thumbv7em-none-eabihf
        run: qemu-system-arm -no-reboot -cpu cortex-m4 -machine netduinoplus2 -nographic -semihosting-config enable=on,target=native -kernel target/thumbv7em-none-eabihf/debug/app

