name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build x86 and run sim
        run: make run
      - name: Build arm hactar12
        run: make build
      - name: Build arm hactar12 mgmt
        run: make build-mgmt
      - name: Run tests
        run: make test
