name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build x86
        run: cargo build --verbose --target=x86_64-unknown-linux-gnu
      - name: Build arm
        run: cargo build --verbose --target=thumbv7em-none-eabihf
      - name: Run tests
        run: cargo test --verbose --target=x86_64-unknown-linux-gnu

