name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build x86
        run: cargo build --verbose --features hal/board-sim,dev/std,app/std,app/exit
      - name: Build arm hactar12
        run: cargo build --verbose --features hal/board-hactar12 --target=thumbv7em-none-eabihf --release
      - name: Build arm blinkA
        run: cargo build --verbose --features hal/board-blinkA --target=thumbv7em-none-eabihf --release
      - name: Run tests
        run: cargo test --verbose --features hal/board-sim,dev/std,app/std
