name: Check the ui-app crate

on:
  push:
    branches: [ main ]
    paths:
      - ".github/**"
      - "ui-app/Cargo.toml"
      - "ui-app/**.rs"
      - "ui-stm32/Cargo.toml"
      - "ui-stm32/**.rs"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/**"
      - "ui-app/Cargo.toml"
      - "ui-app/**.rs"
      - "ui-stm32/Cargo.toml"
      - "ui-stm32/**.rs"

jobs:
  build-and-test:
    name: CI
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
        target: thumbv7em-none-eabihf

    - name: Verify the ui-stm32 crate (ev12)
      uses: ./.github/actions/check-crate
      with:
        path: ./ui-stm32
        build-tests: false
        run-tests: false
        args: --no-default-features -F ev12

    - name: Verify the ui-stm32 crate (ev13)
      uses: ./.github/actions/check-crate
      with:
        path: ./ui-stm32
        build-tests: false
        run-tests: false
        args: --no-default-features -F ev13
