name: ui-tauri

on:
  push:
    branches: [ main ]
    paths:
      - ".github/**"
      - "ui-app/Cargo.toml"
      - "ui-app/**.rs"
      - "ui-tauri/Cargo.toml"
      - "ui-tauri/**.rs"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/**"
      - "ui-app/Cargo.toml"
      - "ui-app/**.rs"
      - "ui-tauri/src-tauri/Cargo.toml"
      - "ui-tauri/src-tauri/**.rs"

jobs:
  build-and-test:
    name: CI
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Verify the ui-tauri crate
      uses: ./.github/actions/check-crate
      with:
        path: ./ui-tauri/src-tauri
        run-tests: false
